### ISSUE TITLE
 ERROR  failed to build APK's

### ISSUE THREAD

**Issue by Aimpxssible** [termuxhackers-id/SARA#13]
Solusinya bang?
![VirtualBox_Kali Linux_13_12_2022_20_05_22](https://user-images.githubusercontent.com/120472813/207333445-7f0f2cde-1c43-405c-b489-907caadce9ab.png)

**Comment by zizomolto** [comment]
have u find a way to fix it i have same problem

**Comment by Aimpxssible** [comment]
I removed 'em then installing again. It's work for me

Pada tanggal Sen, 2 Jan 2023 00.48, zizomolto ***@***.***>
menulis:

**Comment by zizomolto** [comment]
i tried to reinstall and still not working

**Comment by Aimpxssible** [comment]
Try this. https://github.com/Aimpxssible/msfkit
 There is a ransomware generator tool and backdoor generator also

Pada tanggal Sel, 3 Jan 2023 20.33, zizomolto ***@***.***>
menulis:

**Comment by percyjakeson** [comment]
Try this.

Remove your current apk tool and re-install it.

Reinstalling process, follow this video 👍 
https://youtu.be/M9fWezuvTUM

When downloading the apktool.jar, I suggest that you download the apktool_2.4.1.jar

It worked for me.

**Comment by termuxhackers-id** [comment]
fixed, please update
