### ISSUE TITLE
Error failed to build apk

### ISSUE THREAD

**Issue by Shryanshojha745** [termuxhackers-id/SARA#14]
Sir how to solve this 
![Uploading Screenshot_2022-12-14-02-42-44-589_com.termux.jpg…]()

**Comment by zizomolto** [comment]
have u find a way to fix it i have same problem

**Comment by Asad9878** [comment]
Same issue

**Comment by taolagiahuy** [comment]
> Same issue

Same

**Comment by om-bang-jo** [comment]
anda bisa menguninstall sara dan menginstallnya kembali denganperintah ini  git clone https://github.com/termuxhackers-id/SARA && cd SARA && bash installtermux.sh

**Comment by taolagiahuy** [comment]
Bro speak English

**Comment by om-bang-jo** [comment]
you can install SARA and reinstall it with the init command "git clone https://github.com/termuxhackers-id/SARA && cd SARA && bash installtermux.sh"

**Comment by om-bang-jo** [comment]
and one more thing, it doesn't work on android 10 and above

**Comment by taolagiahuy** [comment]
oh so i know the reason why i failed to decompile apk

Vào 20:32, T.2, 9 Th1, 2023 om-bang-jo ***@***.***> đã viết:

**Comment by om-bang-jo** [comment]
yes, my advice, you uninstall and then reinstall it so that the supporting files can be installed perfectly

**Comment by om-bang-jo** [comment]
i hope the developer can update this tool to work on android 10,11 and 12

**Comment by Annxhilator** [comment]
> and one more thing, it doesn't work on android 10 and above

Wait, that repo does not work in newer phones? Seriously?

**Comment by termuxhackers-id** [comment]
fixed, please update
