### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by genzhaa** [termuxhackers-id/SARA#14]
`sh:` 0: Can't open /data/data/https://com.termux/files/home/.suroot/SARA/.data/apktool
I: Using strings https://saraa.apk/res/values/strings.xml
find: ‘https://https://saraa.apk/’: No such file or directory
I: Using smali
[!] Failed to write in file https://saraa.apk/res/values/strings.xml###

**Comment by R1punk** [comment]
try this. for termux

https://github.com /R1punk/SARA

**Comment by eddyray19** [comment]
It's same problem here
