### ISSUE TITLE
Error: Failed to Signed apk's

### ISSUE THREAD

**Issue by alienMak** [termuxhackers-id/SARA#17]
The Apk file is not being generated.

![Screenshot_2021-06-05_22_12_06](https://user-images.githubusercontent.com/54765654/120904983-c8a5aa80-c66c-11eb-8a4a-eb460b2e8417.png)

**Comment by MyhGamer** [comment]
plus i  have the simple error

**Comment by termuxhackers-id** [comment]
> The Apk file is not being generated.
> 
> ![Screenshot_2021-06-05_22_12_06](https://user-images.githubusercontent.com/54765654/120904983-c8a5aa80-c66c-11eb-8a4a-eb460b2e8417.png)

Please use Java 11 (openjdk-11)
> apt-get install default-jdk
