### ISSUE TITLE
Личный вопрос

### ISSUE THREAD

**Issue by Aleksandr586888** [termuxhackers-id/SARA#19]
Можешь подсказать на чём, писать такие штуки или вообще на какой программе пишется подобное , очень сильно интересно, хочу написать кое какое приложение для себя,  очень заинтересовало, прошу вас подсказать пожалуйста хотя бы, что изучить для создания таких штук

**Comment by termuxhackers-id** [comment]
> Можешь подсказать на чём, писать такие штуки или вообще на какой программе пишется подобное , очень сильно интересно, хочу написать кое какое приложение для себя, очень заинтересовало, прошу вас подсказать пожалуйста хотя бы, что изучить для создания таких штук

Learn about java, kotlin, react and android studio
