### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mrmonkey01** [termuxhackers-id/SARA#20]
Building resources...
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_133101735153659865364621433234426085892.tmp, compile, --dir, /data/data/com.termux/files/home/herramientas/SARA/sara/res, --legacy, -o, /data/data/com.termux/files/home/herramientas/SARA/sara/build/resources.zip]

**Comment by Ghostsarah0042** [comment]
Please fix

**Comment by termuxhackers-id** [comment]
install java 8 and apktool 2.8.1, or git pull and run install.sh
