### ISSUE TITLE
Auto start 

### ISSUE THREAD

**Issue by Investoh47** [termuxhackers-id/SARA#20]
How can I set the generated SARA singed APK to auto start even when I restart my phone until I insert the key?

**Comment by KananIslamzada** [comment]
Sara Doesn't work !!.  Error message: This app was built for an older version of Android. Please Update it. 
Thank You.

**Comment by swatts07** [comment]
same problemit works for an older version of android

**Comment by termuxhackers-id** [comment]
> Sara Doesn't work !!. Error message: This app was built for an older version of Android. Please Update it. Thank You.

I have tested Sara on Android 10 and it works 

![Screenshot_2022-03-09-20-50-27-038_com android settings](https://user-images.githubusercontent.com/82352535/157464248-83a83ff6-b80e-4f6e-afd0-31da40a149ff.jpg)

**Comment by termuxhackers-id** [comment]
![Screenshot_2022-03-09-20-50-57-057_com miui home](https://user-images.githubusercontent.com/82352535/157464814-2d225292-da8a-4c36-a225-dc536beaeca7.jpg)
