### ISSUE TITLE
Not opening 

### ISSUE THREAD

**Issue by Erickk2304** [termuxhackers-id/SARA#24]
I successfully installed it one time and it was running but now it doesn't come it's Sara is already there but not opening again when I am doing it.

**Comment by invincible-core** [comment]
> I successfully installed it one time and it was running but now it doesn't come it's Sara is already there but not opening again when I am doing it.

Version v3 is coming

**Comment by Erickk2304** [comment]
Bro its running again but it's show png not found

**Comment by Erickk2304** [comment]
![Screenshot_2023-08-09-14-02-12-26_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/termuxhackers-id/SARA/assets/127486164/e1131560-35ba-4ef8-9589-a1ab2958cbb9)

**Comment by Erickk2304** [comment]
Oi is everyone dead

**Comment by termuxhackers-id** [comment]
Update for v3.0, for termux user please install on proot-distro (ubuntu or etc)
