### ISSUE TITLE
Failed apk recompiling

### ISSUE THREAD

**Issue by Nedwi-ID** [termuxhackers-id/SARA#26]
I have installed the tool in termux with the help of Ubuntu. I have installed all required packages but I'm facing this error.
Screenshots :

![Picsart_23-08-25_22-54-28-839](https://github.com/termuxhackers-id/SARA/assets/142559089/ce5b85d8-8e43-4a56-b280-6861dca3f69d)
![Picsart_23-08-25_22-52-26-112](https://github.com/termuxhackers-id/SARA/assets/142559089/fa0bb686-62eb-45f5-8172-aa451ec70f15)

**Comment by termuxhackers-id** [comment]
Try decompile and recompile manually, if still error you can try with other version of apktool.

```bash
# decompile
apktool d test.apk 
# recompile 
apktool b test 
# recompile with aapt2
apktool b --use-aapt2 test -o my.apk
```

**Comment by Nedwi-ID** [comment]
> Try decompile and recompile manually, if still error you can try with other version of apktool.
> 
> ```shell
> # decompile
> apktool d test.apk 
> # recompile 
> apktool b test 
> # recompile with aapt2
> apktool b --use-aapt2 test -o my.apk
> ```

Need a tutorial ...

**Comment by Cold-Breazy** [comment]
> > Try decompile and recompile manually, if still error you can try with other version of apktool.
> > ```shell
> > # decompile
> > apktool d test.apk 
> > # recompile 
> > apktool b test 
> > # recompile with aapt2
> > apktool b --use-aapt2 test -o my.apk
> > ```
> 
> Need a tutorial ...

I need full tutorial

**Comment by termuxhackers-id** [comment]
You can try install the apktool from local repo
```bash
sudo apt-get install apktool
```
Then try to decompile the apk file
```apktool d test.apk```

And recompile the decompiled apk path
```apktool b test -o test_new.apk```

Or try with _--use-aapt2_
```apktool b test -o test_new.apk --use-aapt2```

If it's work, you can run **python3 sara.py** for build custom trojan or ransomware 🙂
