### ISSUE TITLE
Update pls

### ISSUE THREAD

**Issue by Annxhilator** [termuxhackers-id/SARA#29]
The ransomware will close if you restart the phone

**Comment by secured-mailer** [comment]
How are you , yea Ive noticed that , have you come up with any ideas
to circumvent , such as making it  persistent theme ?

look forward to hearing back

**Comment by Annxhilator** [comment]
> How are you , yea Ive noticed that , have you come up with any ideas
> to circumvent , such as making it  persistent theme ?
> 
> look forward to hearing back
> 
> On 7/13/22, Annxhilator ***@***.***> wrote:
> > The ransomware will close if you restart the phone
> >
> > --
> > Reply to this email directly or view it on GitHub:
> > https://github.com/termuxhackers-id/SARA/issues/29
> > You are receiving this because you are subscribed to this thread.
> >
> > Message ID: ***@***.***>
> 

Did u guys fixed it? It's working perfectly in the android 7

**Comment by secured-mailer** [comment]
sorry didnt mean to send that to you
