### ISSUE TITLE
Can i ask question?

### ISSUE THREAD

**Issue by pixelrogue163** [termuxhackers-id/SARA#3]
Is there possible to get delete the apps to thr target device?

What if he reset his phone? 

Thank you and Godbless to you.

**Comment by termuxhackers-id** [comment]
> Is there possible to get delete the apps to thr target device?
> 
> What if he reset his phone?
> 
> Thank you and Godbless to you.

It could be but I didn't because it was very dangerous 🙏

**Comment by pixelrogue163** [comment]
> > Is there possible to get delete the apps to thr target device?
> > What if he reset his phone?
> > Thank you and Godbless to you.
> 
> No, this malware is not dangerous. If user forgot the key just restart device and apps not auto run so user can uninstall this app

Ohhh. Im afraid to try this in my device. 🤣
