### ISSUE TITLE
Help me to solve this!!!

### ISSUE THREAD

**Issue by HackerSpl0it** [termuxhackers-id/SARA#31]
I: Using strings sara/res/values/strings.xml
find: ‘sara/’: No such file or directory
I: Using smali
[!] Failed to write in file sara/res/values/strings.xml

**Comment by termuxhackers-id** [comment]
> I: Using strings sara/res/values/strings.xml find: ‘sara/’: No such file or directory I: Using smali [!] Failed to write in file sara/res/values/strings.xml

app folder not found, maybe your apktool is the wrong version. check and install the right version for decompiling 'sara' apk
