### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mamad5-beep** [termuxhackers-id/SARA#4]
Traceback (most recent call last):
  File "/home/sayputt/Tools/SARA/sara.py", line 143, in <module>
    start()
  File "/home/sayputt/Tools/SARA/sara.py", line 122, in start
    with Image.open(path) as target:
AttributeError: __enter

**Comment by termuxhackers-id** [comment]
> Traceback (most recent call last):
> File "/home/sayputt/Tools/SARA/sara.py", line 143, in
> start()
> File "/home/sayputt/Tools/SARA/sara.py", line 122, in start
> with Image.open(path) as target:
> AttributeError: __enter

I never found this error, try clone this repo in home directory 🙏
