### ISSUE TITLE
Can i ask Question ?

### ISSUE THREAD

**Issue by Zeel2323-coder** [termuxhackers-id/SARA#6]
It is possible to autostart app after phone Reboot. And also using app no user intrection like give permission or that king of.if yes then how???

**Comment by termuxhackers-id** [comment]
> It is possible to autostart app after phone Reboot. And also using app no user intrection like give permission or that king of.if yes then how???

It could be but I didn't because it was very dangerous 🙏

**Comment by Zeel2323-coder** [comment]
ok but can you tell only theoretical and education purpose only. For learning Purpose only not to harm anyone. Please plese
