### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/text/StringEscapeUtils

### ISSUE THREAD

**Issue by kepla2000** [termuxhackers-id/SARA#9]
Whenever I run the program , I am encountered with this error. Please I need help

![Screenshot_2022-10-25_12-58-25](https://user-images.githubusercontent.com/58229783/197837231-0bb41d78-77d2-407a-8f5a-1956123d3397.png)

**Comment by termuxhackers-id** [comment]
Make sure the requirement have been installed, check README.md for the version of Package needed

**Comment by kayjess9** [comment]
All the requirements have been met as per readme.md but still the error persist

**Comment by zizomolto** [comment]
i have same error
